export const HIDE_SIDE_MENU = 'ui:HISE_SIDE_MENU';

export const SHOW_SIDE_MENU = 'ui:SHOW_SIDE_MENU';

export const HIDE_BOOK_CREATION_FORM = 'ui:HIDE_BOOK_CREATION_FORM';

export const SHOW_BOOK_CREATION_FORM = 'ui:SHOW_BOOK_CREATION_FORM';

export const SHOW_MAIN_SANDWISH_MENU = 'ui:SHOW_MAIN_SANDWISH_MENU';

export const SHOW_MAIN_RETURN_BUTTON = 'ui:SHOW_MAIN_RETURN_BUTTON';


