export const LOAD_BOOKS_REQUEST = 'books:LOAD_BOOKS_REQUEST';
export const LOAD_BOOKS_SUCCESS = 'books:LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_FAILURE = 'books:LOAD_BOOKS_FAILURE';


export const SAVE_BOOKS_REQUEST = 'books:SAVE_BOOKS_REQUEST';
export const SAVE_BOOKS_SUCCESS = 'books:SAVE_BOOKS_SUCCESS';
export const SAVE_BOOKS_FAILURE = 'books:SAVE_BOOKS_FAILURE';
